logging:
  level:
    cn:
      smallbun:
        screw: debug

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:test}
    username: ${DB_USER:root}
    password: ${DB_PWD:root}

screw:
  engine:
    file-type: WORD
    output-file-name: "database-doc(${DB_NAME})"
    # 输出目录
    output-dir: ./output
  doc:
    title: "Database document"
    organization:
    organization-url:
    version: "1.0"
    description: "Database document"
